-- Добавление полей для полной истории сделок Bybit
ALTER TABLE trades
ADD COLUMN IF NOT EXISTS order_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS order_link_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS order_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS stop_order_type VARCHAR(50),

ADD COLUMN IF NOT EXISTS mark_price DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS mark_iv DECIMAL(10, 6),
ADD COLUMN IF NOT EXISTS index_price DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS trade_iv DECIMAL(10, 6),

ADD COLUMN IF NOT EXISTS exec_value DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS closed_size DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS order_qty DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS order_price DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS leaves_qty DECIMAL(18, 8),

ADD COLUMN IF NOT EXISTS fee_rate DECIMAL(10, 6),
ADD COLUMN IF NOT EXISTS fee_currency VARCHAR(10),
ADD COLUMN IF NOT EXISTS exec_fee_v2 DECIMAL(18, 8),
ADD COLUMN IF NOT EXISTS extra_fees TEXT,

ADD COLUMN IF NOT EXISTS block_trade_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS seq BIGINT,
ADD COLUMN IF NOT EXISTS market_unit VARCHAR(50);

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_trades_order_id ON trades(order_id);
CREATE INDEX IF NOT EXISTS idx_trades_seq ON trades(seq);
