import { OptionRow, PositionModel, ExportData } from '../types';
import apiClient from './api';

class ExportService {
  /**
   * Generate JSON export data
   */
  generateJsonExport(
    options: OptionRow[],
    positions: PositionModel[],
    metadata: {
      underlyingSymbol: string;
      underlyingPrice: number;
      expiry: string;
      daysToExpiry: number;
      atmStrike: number;
      atmIv: number;
    }
  ): ExportData {
    return {
      metadata: {
        timestamp: new Date().toISOString(),
        underlying_symbol: metadata.underlyingSymbol,
        underlying_price: metadata.underlyingPrice,
        expiry: metadata.expiry,
        days_to_expiry: metadata.daysToExpiry,
        atm_strike: metadata.atmStrike,
        atm_iv: metadata.atmIv,
      },
      options: options,
      portfolio_positions: positions,
      ai_summary: this.generateAiSummary(options, positions, metadata),
    };
  }

  /**
   * Generate Markdown export
   */
  generateMarkdownExport(
    options: OptionRow[],
    positions: PositionModel[],
    metadata: {
      underlyingSymbol: string;
      underlyingPrice: number;
      expiry: string;
      daysToExpiry: number;
      atmStrike: number;
      atmIv: number;
    }
  ): string {
    const summary = this.generateAiSummary(options, positions, metadata);
    
    return `# Portfolio Analysis Export
**Timestamp:** ${new Date().toISOString()}
**Underlying:** ${metadata.underlyingSymbol} @ $${metadata.underlyingPrice.toLocaleString()}
**Expiry:** ${metadata.expiry} (${metadata.daysToExpiry} days)
**ATM Strike:** $${metadata.atmStrike.toLocaleString()}
**ATM IV:** ${(metadata.atmIv * 100).toFixed(1)}%

## Portfolio Summary
${summary}

## Positions (${positions.length})
${positions.length > 0 ? positions.map(p => this.formatPositionMarkdown(p)).join('\n\n') : 'No positions'}

## Options Board (${options.length})
${options.length > 0 ? this.formatOptionsTableMarkdown(options) : 'No options data'}

## Risk Metrics
${this.generateRiskMetricsMarkdown(positions)}

## Export Information
- Generated by Bybit Options Risk Engine
- Data as of: ${new Date().toLocaleString()}
- For AI analysis and risk assessment`;
  }

  /**
   * Generate CSV export for options
   */
  generateOptionsCsv(options: OptionRow[]): string {
    const headers = ['Strike', 'Type', 'Bid', 'Ask', 'Mark', 'IV', 'Delta', 'Gamma', 'Vega', 'Theta', 'OI', 'Series'];
    const rows = options.map(option => [
      option.strike,
      option.type,
      option.prices.bid,
      option.prices.ask,
      option.prices.mark,
      option.iv.mark,
      option.greeks.delta,
      option.greeks.gamma,
      option.greeks.vega,
      option.greeks.theta,
      option.liquidity.open_interest,
      option.expiry,
    ]);
    
    return [headers, ...rows].map(row => row.join(',')).join('\n');
  }

  /**
   * Generate CSV export for positions
   */
  generatePositionsCsv(positions: PositionModel[]): string {
    const headers = ['Symbol', 'Side', 'Size', 'Entry', 'Mark', 'P&L', 'Delta', 'Gamma', 'Vega', 'Theta'];
    const rows = positions.map(position => [
      position.symbol,
      position.side,
      position.size,
      position.entry_price || '',
      position.mark_value || '',
      position.unrealized_pnl || '',
      position.greeks.delta_coin,
      position.greeks.gamma_coin,
      position.greeks.vega_usd,
      position.greeks.theta_usd,
    ]);
    
    return [headers, ...rows].map(row => row.join(',')).join('\n');
  }

  /**
   * Download data as file
   */
  downloadFile(content: string | Blob, filename: string, mimeType: string): void {
    let blob: Blob;
    
    if (typeof content === 'string') {
      blob = new Blob([content], { type: mimeType });
    } else {
      blob = content;
    }
    
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Export data from API
   */
  async exportFromApi(): Promise<void> {
    try {
      const blob = await apiClient.exportData();
      const filename = `portfolio-export-${new Date().toISOString().split('T')[0]}.json`;
      const mimeType = 'application/json';
      
      this.downloadFile(blob, filename, mimeType);
    } catch (error) {
      console.error('Export failed:', error);
      throw new Error(`Failed to export data: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  private generateAiSummary(
    _options: OptionRow[],
    positions: PositionModel[],
    metadata: {
      underlyingSymbol: string;
      underlyingPrice: number;
      expiry: string;
      daysToExpiry: number;
      atmStrike: number;
      atmIv: number;
    }
  ): string {
    const totalDelta = positions.reduce((sum, p) => sum + p.greeks.delta_coin, 0);
    const totalTheta = positions.reduce((sum, p) => sum + p.greeks.theta_usd, 0);
    const totalVega = positions.reduce((sum, p) => sum + p.greeks.vega_usd, 0);
    
    const deltaDirection = totalDelta > 0.1 ? 'bullish' : totalDelta < -0.1 ? 'bearish' : 'neutral';
    const thetaDirection = totalTheta > 0 ? 'positive theta (earning)' : 'negative theta (paying)';
    const vegaExposure = totalVega > 1000 ? 'long volatility' : totalVega < -1000 ? 'short volatility' : 'neutral volatility';
    
    const atmIvPercent = (metadata.atmIv * 100).toFixed(1);
    
    return `Portfolio is ${deltaDirection} with total delta of ${totalDelta.toFixed(4)}. ${thetaDirection} $${Math.abs(totalTheta).toFixed(2)}/day. ${vegaExposure} with $${totalVega.toFixed(2)} vega. ATM IV is ${atmIvPercent}% for ${metadata.expiry} expiry.`;
  }

  private formatPositionMarkdown(position: PositionModel): string {
    const pnl = position.unrealized_pnl;
    const pnlStr = pnl !== null ? `**P&L:** $${pnl.toFixed(2)}` : '';
    
    return `- **${position.symbol}** (${position.side} ${position.size})
  ${pnlStr}
  **Greeks:** Δ=${position.greeks.delta_coin.toFixed(4)}, Γ=${position.greeks.gamma_coin.toFixed(6)}, Θ=$${position.greeks.theta_usd.toFixed(2)}/day, ν=$${position.greeks.vega_usd.toFixed(2)}`;
  }

  private formatOptionsTableMarkdown(options: OptionRow[]): string {
    if (options.length === 0) return '';
    
    const headers = ['Strike', 'Type', 'Bid', 'Ask', 'Mark', 'IV', 'Δ', 'Γ', 'ν', 'Θ', 'OI'];
    const rows = options.slice(0, 10).map(option => [
      option.strike.toLocaleString(),
      option.type,
      option.prices.bid.toFixed(1),
      option.prices.ask.toFixed(1),
      option.prices.mark.toFixed(1),
      `${(option.iv.mark * 100).toFixed(1)}%`,
      option.greeks.delta.toFixed(3),
      option.greeks.gamma.toFixed(6),
      option.greeks.vega.toFixed(2),
      option.greeks.theta.toFixed(2),
      option.liquidity.open_interest.toLocaleString(),
    ]);
    
    const table = [
      `| ${headers.join(' | ')} |`,
      `| ${headers.map(() => '---').join(' | ')} |`,
      ...rows.map(row => `| ${row.join(' | ')} |`)
    ].join('\n');
    
    if (options.length > 10) {
      return `${table}\n\n*... and ${options.length - 10} more options*`;
    }
    
    return table;
  }

  private generateRiskMetricsMarkdown(positions: PositionModel[]): string {
    const totalDelta = positions.reduce((sum, p) => sum + p.greeks.delta_coin, 0);
    const totalTheta = positions.reduce((sum, p) => sum + p.greeks.theta_usd, 0);
    const totalVega = positions.reduce((sum, p) => sum + p.greeks.vega_usd, 0);
    const totalGamma = positions.reduce((sum, p) => sum + p.greeks.gamma_coin, 0);
    
    return `- **Total Delta:** ${totalDelta.toFixed(4)} (${totalDelta > 0.1 ? 'Long' : totalDelta < -0.1 ? 'Short' : 'Neutral'})
- **Total Theta:** $${totalTheta.toFixed(2)}/day (${totalTheta > 0 ? 'Earning' : 'Paying'})
- **Total Vega:** $${totalVega.toFixed(2)} (${totalVega > 1000 ? 'Long vol' : totalVega < -1000 ? 'Short vol' : 'Neutral'})
- **Total Gamma:** ${totalGamma.toFixed(6)} (${totalGamma > 0 ? 'Positive' : totalGamma < 0 ? 'Negative' : 'Flat'})`;
  }
}

export default new ExportService();